namespace Avalonia.Controls.Maui.SourceGenerators;

internal static class SourceGenerationHelper
{
    public static string GenerateAvaloniaApp(GeneratorOptions options, string mauiProgramClass)
    {
        var themeVariant = options.ThemeVariant switch
        {
            "Light" => "ThemeVariant.Light",
            "Dark" => "ThemeVariant.Dark",
            _ => "ThemeVariant.Default",
        };

        var themeStatement = options.Theme switch
        {
            "Simple" => "Styles.Add(new global::Avalonia.Themes.Simple.SimpleTheme());",
            _ => "Styles.Add(new global::Avalonia.Themes.Fluent.FluentTheme());",
        };

        return $@"// <auto-generated/>
#nullable enable

using Avalonia;
using Avalonia.Controls.Maui.Platform;
using Avalonia.Styling;
using Microsoft.Maui.Hosting;

namespace {options.RootNamespace};

[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""Avalonia.Controls.Maui.SourceGenerators"", ""1.0.0"")]
internal partial class {options.AppClassName} : MauiAvaloniaApplication
{{
    public override void Initialize()
    {{
        RequestedThemeVariant = {themeVariant};
        {themeStatement}
    }}

    protected override MauiApp CreateMauiApp() => {mauiProgramClass}.CreateMauiApp();
}}
";
    }

    public static string GenerateDesktopProgram(GeneratorOptions options)
    {
        var withInterFont = options.IncludeInterFont
            ? @"
            .WithInterFont()"
            : "";

        return $@"// <auto-generated/>
#nullable enable

using Avalonia;
using System;

namespace {options.RootNamespace};

[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""Avalonia.Controls.Maui.SourceGenerators"", ""1.0.0"")]
internal static partial class AvaloniaDesktopProgram
{{
    [STAThread]
    public static void Main(string[] args) => BuildAvaloniaApp()
        .StartWithClassicDesktopLifetime(args);

    public static AppBuilder BuildAvaloniaApp()
        => AppBuilder.Configure<{options.AppClassName}>()
            .UsePlatformDetect(){withInterFont}
            .LogToTrace();
}}
";
    }
}
